# Generated by Django 5.1.5 on 2025-01-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_book_language_alter_lang_lang_language_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lang',
        ),
    ]
